import Alpine from 'alpinejs';
window.Alpine = Alpine;
import intersect from '@alpinejs/intersect';
Alpine.plugin(intersect);
Alpine.start();

import './cart.js';
import './menu.js';
import './product.js';
import './qty.js';
import './accordion.js';
import './gallery.js';
import './forms.js';
import './insta.js';
import './testimonials.js';
import './sauces.js';
import './logos.js';
import './hero.js';
import './newsletter.js';
import './login.js';
import './password.js';
